> ### **Numpy Basic**

In [5]:
import numpy as np

In [11]:
arr_1d = np.array([1,2,3,4])
print("1D array :\n",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("\n2D array :\n",arr_2d)

1D array :
 [1 2 3 4]

2D array :
 [[1 2 3]
 [4 5 6]]


> #### **list vs Array**

In [ ]:
py_list = [1,2,3,4]
print("Python list multiplication : " , py_list *2)

np_arr = np.array([1,3,4,5]) # element wise multiplication
print("Numpy Array multiplication : " , np_arr *2)

Python list multiplication :  [1, 2, 3, 4, 1, 2, 3, 4]
Numpy Array multiplication :  [ 2  6  8 10]


In [14]:
import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ",time.time()- start)

start = time.time()
np_arr = np.arange(1000000) *2
print("\n Numpy operation time: ",time.time()- start)


 List operation time:  0.12230181694030762

 Numpy operation time:  0.012505769729614258


> ### **Creating array from scratch**

In [ ]:
zeros = np.zeros((3,4)) # for the only 0's Matrix
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones = np.ones((3,4)) # for the only 1's Matrix
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
full = np.full((3,3),7) # for the constant values
print(full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
random = np.random.random((3,3)) # for the random number Matrix
print(random)

[[0.81185316 0.67178536 0.57337815]
 [0.56326174 0.08120345 0.76886233]
 [0.6573364  0.17341143 0.20887627]]


In [ ]:
seq = np.arange(0,11,2) 
print(seq)

[ 0  2  4  6  8 10]


> ### **Vector, Matrix, Tensor**

In [25]:
vector = np.array([1,2,3,4])
print(vector)

[1 2 3 4]


In [27]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])

print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


> ### **Array Properties**

In [33]:
arr = np.array([[1,2,3],
               [4,5,6]])

print("Shape : ",arr.shape)
print("Dimension : ",arr.ndim)
print("Size : ",arr.size)
print("Datatype : ",arr.dtype)

Shape :  (2, 3)
Dimension :  2
Size :  6
Datatype :  int64


> ### **Array Reshaping**

In [43]:
arr = np.arange(12)
print("Original Array :",arr)

reshaped = arr.reshape((3,4))
print("\nReshaped Array :\n",reshaped)

flattend = reshaped.flatten() # this return the copy of the original array
print("\nFlattend Array :\n",flattend)

# Ravel (return view, insted of copy)
# Means it return the original array.

raveled = reshaped.ravel()
print("\nRaveled Array :\n",raveled)

# Transpose 
transpose = reshaped.T
print("\nTranspose Array :\n",transpose)


Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattend Array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled Array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose Array :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
