> ### **Numpy Array operations**

In [3]:
import numpy as np

In [4]:
# 1D array slicing

arr = np.arange(10)
print('Basic slicing : ',arr[2:7])
print('Index slicing : ',arr[1:8:2])
print('Negative slicing : ',arr[-3])

Basic slicing :  [2 3 4 5 6]
Index slicing :  [1 3 5 7]
Negative slicing :  7


In [5]:
# 2D array slicing

arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific element: ",arr_2d[1,2])
print('Entire Row: ', arr_2d[1])
print('Entire col: ', arr_2d[:,1])

Specific element:  6
Entire Row:  [4 5 6]
Entire col:  [2 5 8]


> ### **Sorting**

In [6]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print('Sorted Array: ', np.sort(unsorted))

Sorted Array:  [1 1 2 3 4 5 6 9]


In [7]:
unsorted_2d = np.array([[3,2],[1,2],[3,1]])
print("Sorted Array: ", np.sort(unsorted_2d, axis=0))
# sorted by top to bottom

Sorted Array:  [[1 1]
 [3 2]
 [3 2]]


> ### **Filter**

In [8]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_no = numbers[numbers % 2 == 0] # numpy allow us to use expressions also
print(even_no)

[ 2  4  6  8 10]


> ### **Filter with mask**

In [9]:
mask = numbers > 5
print("Number is Greater then 5 : ", numbers[mask])

Number is Greater then 5 :  [ 6  7  8  9 10]


> ### **Fancy Indexing vs Numpy Where**

In [10]:
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
indices = [0,2,4]
print(numbers[indices])

[1 3 5]


In [14]:
# where is like to Mask 
where_result = np.where(numbers>5) 
print(where_result)
print(numbers[where_result])

(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


In [18]:
codition_arr = np.where(numbers>5,numbers*4,numbers)
print(codition_arr)

[ 1  2  3  4  5 24 28 32 36 40]


In [19]:
#  if(numbers > 5){
#     numbers * 4
#  } else{
#     numbers
# }

In [20]:
codition_arr = np.where(numbers>5,True,False)
print(codition_arr)

[False False False False False  True  True  True  True  True]


> ### **Add and removing data**

In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

#combine = arr1 + arr2 # normal combination means it add the numbers together
combine = np.concatenate((arr1,arr2)) # The concatenate means add all numbers together not sum of them
print(combine)

[1 2 3 4 5 6]


> ### **Array Compatibilty**

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6,10])
c = np.array([7,8,9])

print("Compatibilty shape :",a.shape == b.shape)


Compatibilty shape : False


In [32]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row)) # add the new row = vstack
print(original)
print("\n",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("\n",with_new_col)

[[1 2]
 [3 4]]

 [[1 2]
 [3 4]
 [5 6]]

 [[1 2 7]
 [3 4 8]]


In [34]:
# delete 
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print(deleted)

[1 2 4 5]
