# Task 1

> ### **Basics – Array Creation & Inspection**

In [1]:
import numpy as np

In [ ]:
# Create a 1D NumPy array with numbers from 1 to 10.

arr_1d = np.arange(10)
print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Create a 3×3 matrix filled with True values.

trueVal  = np.full((3,3),True)
print(trueVal)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#Create an array of 50 zeros and change the 10th element to 5.

zeros = np.zeros((50))
change_ele = zeros[9] = 5
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [14]:
#Generate an array of 10 random integers between 1 and 100.

random_integers = np.random.randint(1, 101, size=10)
print(random_integers)

[ 97  39  51  41  81  27 100  93  30  90]


In [13]:
#Check the shape, size, and data type of an array.

print("Shape : ",arr_1d.shape)
print("Dimension : ",arr_1d.ndim)
print("Size : ",arr_1d.size)
print("Datatype : ",arr_1d.dtype)
print("============================================")
print("Shape : ",trueVal.shape)
print("Dimension : ",trueVal.ndim)
print("Size : ",trueVal.size)
print("Datatype : ",trueVal.dtype)
print("============================================")
print("Shape : ",zeros.shape)
print("Dimension : ",zeros.ndim)
print("Size : ",zeros.size)
print("Datatype : ",zeros.dtype)
print("============================================")
print("Shape : ",random_integers.shape)
print("Dimension : ",random_integers.ndim)
print("Size : ",random_integers.size)
print("Datatype : ",random_integers.dtype)

Shape :  (10,)
Dimension :  1
Size :  10
Datatype :  int64
Shape :  (3, 3)
Dimension :  2
Size :  9
Datatype :  bool
Shape :  (50,)
Dimension :  1
Size :  50
Datatype :  float64
Shape :  (10,)
Dimension :  1
Size :  10
Datatype :  int32


# Task 2

In [16]:
arr = np.arange(20)
print(arr[0:21:2])

[ 0  2  4  6  8 10 12 14 16 18]


In [34]:

arr1 = np.array([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15],
                 [16,17,18,19,20],
                 [21,22,23,24,25]])
print("Main Array : \n",arr1)
print("\n Middle elements\n",arr1[1:4,1:4])


Main Array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 Middle elements
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [37]:
arr = np.arange(20)
print('Original Array: ',arr)
print("\nReversed Array: ",arr[::-1])

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reversed Array:  [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [39]:
arr = np.array([-1,-5,-4,-2,-5,-15,-18,-25,-85,7])
arr[arr<0] = 0
print(arr)


[0 0 0 0 0 0 0 0 0 7]


In [40]:
arr = np.array([[1,  2,  3,  4],
                [5,  6,  7,  8],
                [9, 10, 11, 12],
                [13,14, 15, 16]])

digonal = np.diag(arr)
print(digonal)

[ 1  6 11 16]


# Task 3

In [41]:
num1 = np.array([1,2,3,4,5])
num2 = np.array([[9,8,7,6,5]])

print(num1+num2)

[[10 10 10 10 10]]


In [42]:
num1 = np.array([1,2,3,4,5])
print(num1*3)

[ 3  6  9 12 15]


In [47]:
num1 = np.array([4,16,25,32])
print(np.sqrt(num1))

[2.         4.         5.         5.65685425]


In [49]:
num1 = np.array([1,2,3,4,5])
print(np.min(num1))
print(np.median(num1))
print(np.std(num1))

1
3.0
1.4142135623730951


In [50]:
arr = np.array([5, 10, 15, 20, 25])
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(normalized)

[0.   0.25 0.5  0.75 1.  ]
